spring.application.name=ProductService
server.port=8081

# Database Configuration (H2, MySQL, PostgreSQL)
spring.datasource.url=jdbc:h2:mem:zion_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Enable H2 Console
spring.h2.console.enabled=true

# JPA Config
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Enable Feign Client
spring.main.allow-bean-definition-overriding=true

#For actuator
management.endpoints.web.exposure.include=*
management.endpoint.info.enabled=true

#For Eureka
eureka.client.serviceUrl.defaultZone=${EUREKA_URI:http://localhost:8761/eureka/}
#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Instance details
eureka.instance.prefer-ip-address=true
#eureka.instance.hostname=$servicedirectory_host
eureka.instance.hostname=localhost


#spring.kafka.bootstrap-servers=${KAFKA_URI:http://localhost:9092}
#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.template.default-topic=productTopic



spring.security.user.name= admin
spring.security.user.password= admin


logging.file.name=/logs/zion.log
logging.level.root=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Send logs to Logstash
logging.logback.appender.logstash.destination=localhost:5044